openapi: 3.0.0
info:
  description: REST service API.
  version: 1.0.1
  title: AFarCloud REST API
  contact:
    name: Vicente Hernández Díaz
    email: vicente.hernandez@upm.es 
externalDocs:
   description: Find out more about AFarCloud
   url: http://www.afarcloud.eu/    
tags:
  - name: POST Telemetry
  - name: Test your JSON data format
paths:
  "/{scenario}/telemetry":
    post:
      tags:
        - POST Telemetry
      summary: Post telemetry data  
      operationId: getMeasure 
      parameters:
        - name: scenario
          in: path
          description: AFarCloud scenario ("as01" to "as11")
          required: true
          schema:
            type: string
            pattern: as01|as02|as03|as04|as05|as06|as07|as08|as09|as10|as11
      requestBody:
        content:
          application/json:
            schema:
             oneOf:
                - $ref: 'https://localhost:8080/schemas/AggregationMthroughGatewaySchema_SLS.json'
                - $ref: 'https://localhost:8080/schemas/CollarSchema.json'
                - $ref: 'https://localhost:8080/schemas/CollarSchemaList.json'
                - $ref: 'https://localhost:8080/schemas/RegionSchema.json'
                - $ref: 'https://localhost:8080/schemas/RegionSchemaList.json'
                - $ref: 'https://localhost:8080/schemas/SensorAccumulatedMeasurements_Simplified.json'
                - $ref: 'https://localhost:8080/schemas/SimpleMeasurementSchema_Simplified.json'
                - $ref: 'https://localhost:8080/schemas/SimpleMeasurementSchema_SLS.json'
                - $ref: 'https://localhost:8080/schemas/VariousMfromMultiSensorSchema_SLS.json'
                - $ref: 'https://localhost:8080/schemas/VariousMfromSensorSchema_SLS.json'
            examples:
              SensorMeasure: 
               value: {
                resourceId: 'urn:afc:AS04:environmentalObservations:TST:airSensor:airTemperatureSensor0012',
                sequenceNumber: 123,
                location:
                {
                  latitude: 45.45123,
                  longitude: 25.25456,
                  altitude: 2.10789
                },
                observedProperty: air_temperature,
                resultTime: 1558086914,
                result:
                {
                  value: 3.2,
                  uom: 'http://qudt.org/vocab/unit/DEG_C'    
                }
              }
              RegionMeasure: 
               value: {
                resourceId: 'urn:afc:AS04:environmentalObservations:TST:airSensor:airTemperatureSensor0012',
                sequenceNumber: 123,
                location:
                {
                  latitude: 45.45123,
                  longitude: 25.25456,
                  altitude: 2.10789
                },
                observedProperty: air_temperature,
                resultTime: 1558086914,
                result:
                {
                  value: 3.2,
                  uom: 'http://qudt.org/vocab/unit/DEG_C'    
                }
              }
             
              
        required: true
      responses:
        "200":
          description: "Successful operation"
        "405":
          description: "Invalid input: not AFarCloud-compliant"
        "415":
          description: "Invalid input: not a JSON"
  "/{scenario}/telemetry?test":
    post:
      tags:
        - Test your JSON data format
      summary: Test JSON  
      operationId: testMeasure
      parameters:
        - name: scenario
          in: path
          description: AFarCloud scenario ("as01" to "as11")
          required: true
          schema:
            type: string
            pattern: as01|as02|as03|as04|as05|as06|as07|as08|as09|as10|as11
      requestBody:
        content:
          application/json:
            schema:
             oneOf:
                - $ref: 'https://localhost:8080/schemas/AggregationMthroughGatewaySchema_SLS.json'
                - $ref: 'https://localhost:8080/schemas/CollarSchema.json'
                - $ref: 'https://localhost:8080/schemas/CollarSchemaList.json'
                - $ref: 'https://localhost:8080/schemas/RegionSchema.json'
                - $ref: 'https://localhost:8080/schemas/RegionSchemaList.json'
                - $ref: 'https://localhost:8080/schemas/SensorAccumulatedMeasurements_Simplified.json'
                - $ref: 'https://localhost:8080/schemas/SimpleMeasurementSchema_Simplified.json'
                - $ref: 'https://localhost:8080/schemas/SimpleMeasurementSchema_SLS.json'
                - $ref: 'https://localhost:8080/schemas/VariousMfromMultiSensorSchema_SLS.json'
                - $ref: 'https://localhost:8080/schemas/VariousMfromSensorSchema_SLS.json'
            example:
              {
                resourceId: 'urn:afc:AS04:environmentalObservations:TST:airSensor:airTemperatureSensor0012',
                sequenceNumber: 123,
                location:
                {
                  latitude: 45.45123,
                  longitude: 25.25456,
                  altitude: 2.10789
                },
                observedProperty: air_temperature,
                resultTime: 1558086914,
                result:
                {
                  value: 3.2,
                  uom: 'http://qudt.org/vocab/unit/DEG_C'    
                }
              }
                
        required: true
      responses:
        "200":
          description: "Successful operation"
        "405":
          description: "Invalid input: not AFarCloud-compliant"
        "415":
          description: "Invalid input: not a JSON"

servers:
  - url: https://localhost:8080/
    description: Torcos      
